import { Document, Page, Text, View, StyleSheet, Svg, Rect, Circle } from '@react-pdf/renderer'
import type { DbRecommendation } from '@/features/analysis/types'

const VIOLET = '#7c3aed'
const MUTED = '#64748b'
const LIGHT_BG = '#f8fafc'
const BORDER = '#e2e8f0'

const styles = StyleSheet.create({
  page: { fontFamily: 'Helvetica', backgroundColor: '#ffffff', paddingVertical: 48, paddingHorizontal: 52 },
  footer: { position: 'absolute', bottom: 24, left: 52, right: 52, borderTopWidth: 1, borderTopColor: BORDER, paddingTop: 8 },
  footerText: { fontSize: 8, color: MUTED },
  coverTitle: { fontSize: 26, fontFamily: 'Helvetica-Bold', color: '#0f172a', marginBottom: 8 },
  coverSub: { fontSize: 12, color: MUTED, marginBottom: 32 },
  sectionLabel: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: MUTED, textTransform: 'uppercase', letterSpacing: 1, marginBottom: 6 },
  summaryRow: { flexDirection: 'row', gap: 24, marginBottom: 24 },
  summaryBox: { flex: 1, backgroundColor: LIGHT_BG, borderRadius: 6, padding: 12 },
  summaryValue: { fontSize: 22, fontFamily: 'Helvetica-Bold', color: VIOLET },
  summaryLabel: { fontSize: 9, color: MUTED, marginTop: 2 },
  // Rec card
  recPage: { fontFamily: 'Helvetica', backgroundColor: '#ffffff', paddingVertical: 48, paddingHorizontal: 52 },
  badge: { backgroundColor: VIOLET, borderRadius: 4, paddingVertical: 2, paddingHorizontal: 6, alignSelf: 'flex-start', marginBottom: 10 },
  badgeText: { fontSize: 9, fontFamily: 'Helvetica-Bold', color: '#ffffff' },
  hypothesis: { fontSize: 14, fontFamily: 'Helvetica-Bold', color: '#0f172a', lineHeight: 1.4, marginBottom: 12 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 14 },
  chip: { backgroundColor: LIGHT_BG, borderRadius: 10, paddingVertical: 3, paddingHorizontal: 8 },
  chipText: { fontSize: 8, color: MUTED },
  sectionTitle: { fontSize: 9, fontFamily: 'Helvetica-Bold', color: MUTED, textTransform: 'uppercase', letterSpacing: 0.8, marginBottom: 4 },
  evidenceItem: { fontSize: 9, color: '#334155', marginBottom: 3, paddingLeft: 8 },
  pmBox: { backgroundColor: '#f5f3ff', borderRadius: 6, padding: 10, marginTop: 10 },
  pmLabel: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: VIOLET, marginBottom: 3 },
  pmText: { fontSize: 9, color: '#334155', lineHeight: 1.4 },
  divider: { borderBottomWidth: 1, borderBottomColor: BORDER, marginVertical: 12 },
})

function Footer() {
  return (
    <View style={styles.footer} fixed>
      <Text style={styles.footerText}>Generated by Experiment Intelligence</Text>
    </View>
  )
}

function MatrixDot({ priority, experimentType }: { priority: number; experimentType: string }) {
  const EFFORT_MAP: Record<string, number> = {
    'A/B Test': 0.15, 'Feature Flag': 0.25, 'Holdout': 0.5, 'Bandit': 0.6, 'Multivariate': 0.85,
  }
  const x = (EFFORT_MAP[experimentType] ?? 0.5) * 120 + 10
  const y = (1 - (priority <= 2 ? 0.8 : priority === 3 ? 0.5 : 0.2)) * 80 + 10
  const color = priority <= 2 ? VIOLET : '#94a3b8'
  return <Circle cx={x} cy={y} r={5} fill={color} />
}

interface Props {
  projectName: string
  analysisDate: string
  model: string
  recommendations: DbRecommendation[]
}

export function RecommendationsPDF({ projectName, analysisDate, model, recommendations }: Props) {
  return (
    <Document title={`${projectName} — Recommendations`} author="Experiment Intelligence">
      {/* Cover page */}
      <Page size="A4" style={styles.page}>
        <Text style={styles.coverTitle}>{projectName}</Text>
        <Text style={styles.coverSub}>AI Experiment Recommendations · {analysisDate}</Text>
        <Text style={{ fontSize: 9, color: MUTED, marginBottom: 24 }}>Model: {model}</Text>

        {/* Summary stats */}
        <View style={styles.summaryRow}>
          <View style={styles.summaryBox}>
            <Text style={styles.summaryValue}>{recommendations.length}</Text>
            <Text style={styles.summaryLabel}>Recommendations</Text>
          </View>
          <View style={styles.summaryBox}>
            <Text style={styles.summaryValue}>
              {recommendations.filter(r => r.priority <= 2).length}
            </Text>
            <Text style={styles.summaryLabel}>High Priority</Text>
          </View>
          <View style={styles.summaryBox}>
            <Text style={styles.summaryValue}>
              {Math.round(recommendations.reduce((a, r) => a + r.confidence, 0) / Math.max(recommendations.length, 1) * 100)}%
            </Text>
            <Text style={styles.summaryLabel}>Avg Confidence</Text>
          </View>
        </View>

        {/* Impact/Effort matrix */}
        <Text style={styles.sectionLabel}>Impact / Effort Matrix</Text>
        <View style={{ borderWidth: 1, borderColor: BORDER, borderRadius: 6, padding: 4, marginBottom: 24 }}>
          <Svg width={140} height={100} viewBox="0 0 140 100">
            <Rect x={0} y={0} width={140} height={100} fill={LIGHT_BG} rx={4}/>
            {recommendations.map(r => (
              <MatrixDot key={r.id} priority={r.priority} experimentType={r.experiment_type} />
            ))}
          </Svg>
        </View>

        <Footer />
      </Page>

      {/* One page per recommendation */}
      {recommendations.map((rec) => (
        <Page key={rec.id} size="A4" style={styles.recPage}>
          <View style={styles.badge}>
            <Text style={styles.badgeText}>P{rec.priority} · {rec.experiment_type}</Text>
          </View>
          <Text style={styles.hypothesis}>{rec.hypothesis}</Text>

          <View style={styles.chipRow}>
            <View style={styles.chip}>
              <Text style={styles.chipText}>{Math.round(rec.confidence * 100)}% confidence</Text>
            </View>
            {rec.estimated_reach != null && rec.estimated_reach > 0 && (
              <View style={styles.chip}>
                <Text style={styles.chipText}>~{rec.estimated_reach.toLocaleString()} users reach</Text>
              </View>
            )}
            {rec.target_segments?.map(s => (
              <View key={s.segment_id} style={[styles.chip, { backgroundColor: '#f5f3ff' }]}>
                <Text style={[styles.chipText, { color: VIOLET }]}>{s.segment_name}</Text>
              </View>
            ))}
          </View>

          <View style={styles.divider} />

          <Text style={styles.sectionTitle}>Evidence</Text>
          {rec.evidence.map((e, i) => (
            <Text key={i} style={styles.evidenceItem}>• {e}</Text>
          ))}

          {rec.rationale && (
            <>
              <View style={styles.divider} />
              <Text style={styles.sectionTitle}>Rationale</Text>
              <Text style={{ fontSize: 9, color: '#334155', lineHeight: 1.4 }}>{rec.rationale}</Text>
            </>
          )}

          {rec.pm_summary && (
            <View style={styles.pmBox}>
              <Text style={styles.pmLabel}>What to tell your team</Text>
              <Text style={styles.pmText}>{rec.pm_summary}</Text>
            </View>
          )}

          <Footer />
        </Page>
      ))}
    </Document>
  )
}
